name: CI Pipeline Exemplo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Rodar um comando de teste
      run: echo "Olá, seu pipeline rodou com sucesso!"
